name: Run dyno on PR open

on:
  pull_request:
    types:
      - opened

jobs:
  run-dyno:
    if: ${{ github.event.pull_request.merged == false }}
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Modify sysctl settings
      run: |
        echo "kernel.perf_event_paranoid=-1" | sudo tee -a /etc/sysctl.conf
        echo "kernel.kptr_restrict=0" | sudo tee -a /etc/sysctl.conf
        sudo sysctl -p /etc/sysctl.conf

    - name: Extract PR number
      id: extract_pr_number
      run: |
        echo "PR_NUMBER=$(echo "${{ github.event.pull_request.url }}" | grep -o '[0-9]*$')" >> $GITHUB_ENV

    - name: Fetch PR reference
      run: |
        git fetch origin pull/${{ env.PR_NUMBER }}/head:pr-${{ env.PR_NUMBER }}

    - name: Check out PR branch
      run: |
        git checkout pr-${{ env.PR_NUMBER }}
        
    - name: Extract PR hash
      id: extract_pr_hash
      run: |
        PR_HASH=$(git rev-parse HEAD)
        echo "PR_HASH=$PR_HASH" >> $GITHUB_ENV

    - name: Get PR title and URL
      id: get_pr_details
      run: |
        PR_DETAILS=$(curl -s -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.pull_request.head.repo.name }}/pulls/${{ env.PR_NUMBER }}")
        PR_TITLE=$(echo "$PR_DETAILS" | jq -r '.title')
        PR_URL=$(echo "$PR_DETAILS" | jq -r '.html_url')
        echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
        echo "PR_URL=$PR_URL" >> $GITHUB_ENV

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ env.AWS_REGION }}

    - name: Download data from S3
      run: |
        aws s3 sync s3://${{ env.S3_BUCKET }}/site/data /home/runner/work/benchmarks

    - name: Build sway
      run: |
        cargo build --release --features profiler

    - name: Install dyno tool
      run: |
        cd /home/runner/work/
        mkdir profiler
        cd profiler
        git clone https://github.com/ourovoros-io/dyno.git
        cd dyno
        cargo build --release
        cp target/release/dyno /home/runner/work/
        sudo rm -rf /home/runner/work/profiler
    
    - name: Run dyno tool
      run: |
        cd /home/runner/work/
        ./dyno -t sway/sway/test/src/sdk-harness/test_projects/hashing/ -f sway/sway/target/release/forc --flamegraph

    - name: Install Dyno Site
      run: |
        cd /home/runner/work/
        mkdir sitebuilder
        cd sitebuilder
        git clone https://github.com/ourovoros-io/dynosite.git
        cd dynosite
        cargo build --release
        cp target/release/dynosite /home/runner/work/
        sudo rm -rf /home/runner/work/sitebuilder

    - name: Run Dyno Site
      run: |
        cd /home/runner/work/ 
        ./dynosite -b /home/runner/work/benchmarks -p "${{ env.PR_HASH }}" -t "${{ env.PR_TITLE }}" -l "${{ env.PR_URL }}" 

    - name: Upload generated files to S3
      run: |
        aws s3 sync /home/runner/work/site/data s3://${{ env.S3_BUCKET }}/site/data
        aws s3 cp /home/runner/work/site/error.html s3://${{ env.S3_BUCKET }}/site/error.html
        aws s3 cp /home/runner/work/site/index.html s3://${{ env.S3_BUCKET }}/site/index.html

    - name: Update README
      run: |
        echo "[View the generated index.html](https://${{ env.S3_BUCKET }}.s3.${{ env.AWS_REGION }}.amazonaws.com/site/index.html)" > README.md